---
layout: cv
title: Michael Blazzard
---
# MICHAEL BLAZZARD  
Mjblazz77@gmail.com, 435-300-1449, LinkedIn: Michael Blazzard

## EDUCATION  
**Bachelor of Science in Accounting**  
*January 2021 - December 2024*  
Brigham Young University - Idaho, Rexburg, ID  
- Relevant coursework: Financial Accounting, Managerial Accounting, Cost Accounting, Income - Tax 1 & 2  
- Public Speaking, Business Analytics, Principles of Leadership  

## EXPERIENCE  
**Internship**  
*April 2024*  
BGB CPA, Kamas, UT  
- Completed personal and business tax returns for clients in DRAKE  
- Reconciled client accounts and maintained accurate books in QBO and QB Desktop  
- Assisted with financial accounting for large companies in Microsoft Dynamics GP  
- Aided in tax preparation and ensured accuracy of financial statements  

**CPA Assistant**  
*January 2020 - Present*  
BGB CPA, Kamas, UT  
- Trusted with client relations and information gathering  
- Managed payroll and monitored client accounts  
- Reconciled accounts and categorized transactions for numerous clients  

## VOLUNTEER EXPERIENCE  
**Missionary**  
*August 2019 - October 2020*  
The Church of Jesus Christ of Latter-Day Saints, Philippines  
- Became fluent in Tagalog, their national language  
- Thrived in a new country and developed leadership skills  
- Spent countless hours serving and helping others with various needs  

## SKILLS  
- Proficient in Excel/VBA  
- Microsoft Power BI/Tableau  
- QuickBooks Desktop/Online  
- DRAKE Tax Software  
- SQL/Python  
- Experience in Microsoft Dynamics GP  




<!-- ### Footer

Last updated: Dec 9, 2024 -->